# MIRIX配置文件 - Docker环境
version: "1.0"

# 服务配置
server:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  log_level: "info"
  reload: false

# 数据库配置
database:
  # PostgreSQL配置
  postgres:
    host: "${POSTGRES_HOST:-postgres}"
    port: "${POSTGRES_PORT:-5432}"
    database: "${POSTGRES_DB:-mirix_memory}"
    username: "${POSTGRES_USER:-mirix}"
    password: "${POSTGRES_PASSWORD:-mirix_password}"
    pool_size: 10
    max_overflow: 20
    echo: false
    
  # Redis配置
  redis:
    host: "${REDIS_HOST:-redis}"
    port: "${REDIS_PORT:-6379}"
    db: 0
    password: "${REDIS_PASSWORD:-}"
    max_connections: 10

# 向量数据库配置
vector_db:
  provider: "pgvector"
  embedding_dim: 1536
  distance_metric: "cosine"
  index_type: "ivfflat"

# 记忆系统配置
memory:
  # 六种记忆类型配置
  types:
    core:
      enabled: true
      retention_days: -1  # 永久保存
      max_entries: 1000
    episodic:
      enabled: true
      retention_days: 365
      max_entries: 10000
    semantic:
      enabled: true
      retention_days: -1  # 永久保存
      max_entries: 50000
    procedural:
      enabled: true
      retention_days: -1  # 永久保存
      max_entries: 5000
    resource:
      enabled: true
      retention_days: 180
      max_entries: 20000
    knowledge:
      enabled: true
      retention_days: -1  # 永久保存
      max_entries: 100000
  
  # 记忆检索配置
  retrieval:
    similarity_threshold: 0.7
    max_results: 20
    enable_reranking: true
    
  # 记忆清理配置
  cleanup:
    enabled: true
    interval_hours: 24
    batch_size: 1000

# LLM配置
llm:
  default_provider: "${DEFAULT_LLM_PROVIDER:-ollama}"
  providers:
    ollama:
      api_url: "${OLLAMA_BASE_URL:-http://ollama:11434}"
      default_model: "${DEFAULT_LLM_MODEL:-llama3.2:1b}"
      timeout: 60
      max_retries: 3
    openai:
      api_key: "${OPENAI_API_KEY:-}"
      api_base: "${OPENAI_API_BASE:-https://api.openai.com/v1}"
      default_model: "gpt-3.5-turbo"
      timeout: 30
      max_retries: 3
    anthropic:
      api_key: "${ANTHROPIC_API_KEY:-}"
      default_model: "claude-3-haiku-20240307"
      timeout: 30
      max_retries: 3

# 嵌入模型配置
embedding:
  default_provider: "ollama"
  providers:
    ollama:
      api_url: "${OLLAMA_BASE_URL:-http://ollama:11434}"
      model: "mxbai-embed-large"
    openai:
      api_key: "${OPENAI_API_KEY:-}"
      model: "text-embedding-ada-002"

# 多模态配置
multimodal:
  # 屏幕捕获（容器中禁用）
  screen_capture:
    enabled: "${ENABLE_SCREEN_CAPTURE:-false}"
    interval_seconds: 30
    quality: 80
    
  # 音频捕获（容器中禁用）
  audio_capture:
    enabled: "${ENABLE_AUDIO_CAPTURE:-false}"
    sample_rate: 16000
    channels: 1
    
  # 文件处理
  file_processing:
    enabled: true
    max_file_size_mb: 100
    supported_formats:
      - "pdf"
      - "txt"
      - "md"
      - "docx"
      - "png"
      - "jpg"
      - "jpeg"

# 安全配置
security:
  api_key_required: false
  cors_origins:
    - "http://localhost:8080"
    - "http://aienhance:8080"
  rate_limiting:
    enabled: true
    requests_per_minute: 100

# 日志配置
logging:
  level: "${LOG_LEVEL:-info}"
  format: "json"
  file: "/app/logs/mirix.log"
  rotation: "midnight"
  retention: 7

# 监控配置
monitoring:
  metrics_enabled: true
  tracing_enabled: true
  health_check_interval: 30

# 性能配置
performance:
  cache_ttl_seconds: 3600
  batch_processing_size: 100
  max_concurrent_requests: 50
  memory_limit_mb: 2048

# 功能特性开关
features:
  auto_summarization: true
  context_analysis: true
  relationship_extraction: true
  emotional_analysis: false
  privacy_mode: true